M48
; DRILL file {KiCad 9.0.7} date 2026-02-28T16:41:58+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-28T16:41:58+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X16.764Y-59.848
X17.018Y-16.764
X48.26Y-16.764
X48.26Y-59.848
M30
